name: Evaluate PR

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install and test
      run: |
        npm ci
        npm test
    - name: check lint rules according to standard
      run: npm run standard
